# Spring properties
spring:
  application:
    name: Application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cdr?verifyServerCertificate=false&useSSL=false&requireSSL=false&characterEncoding=UTF-8
    username: root
    password: 1111
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:      
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    br.com.sdvs.cdr: INFO