# Spring properties
spring:
  h2:
    console:
      enabled: true
      path: /h2
      url: jdbc:h2:file:~/test
  datasource:
    username: sa
    password: 
    driver-class-name: org.h2.Driver
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    br.com.sdvs.cdr: INFO